# name: kam_wala_app
# description: "A professional Flutter app with Admin, User, and Worker panels."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ">=3.7.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   # Firebase core
#   firebase_core: ^3.15.2
  
#   cloud_firestore: ^5.5.1
#   firebase_storage: ^12.1.1

#   # State management
#   provider: ^6.1.5

#   # UI
#   cupertino_icons: ^1.0.8
#   flutter_spinkit: ^5.2.0
#   google_fonts: ^6.1.0

#   # Image picker
#   image_picker: ^1.1.1

#   # Local storage
#   shared_preferences: ^2.2.3

#   # Internet connection check
#   connectivity_plus: ^5.0.2

#   # Navigation
#   go_router: ^14.1.2

#   # For splash screen and animations
#   flutter_native_splash: ^2.4.0
#   animated_text_kit: ^4.2.2

#   # Date/time picker
#   intl: ^0.19.0
#   lottie: ^3.3.1
#   flare_flutter: ^3.0.2
#   firebase_auth: ^5.7.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# flutter:

#   uses-material-design: true

#   # assets:
#   #   - assets/images/
#   #   - assets/icons/
#   #   - assets/logos/

#   # fonts:
#   #   - family: Poppins
#   #     fonts:
#   #       - asset: assets/fonts/Poppins-Regular.ttf
#   #       - asset: assets/fonts/Poppins-Bold.ttf
#   #         weight: 700
#   #       - asset: assets/fonts/Poppins-Italic.ttf
#   #         style: italic


name: kam_wala_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  flutter_svg_provider: ^1.0.7
  firebase_auth: ^5.7.0
  flutter_easyloading: ^3.0.5
  cloud_firestore: ^5.6.12
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3
  animations: ^2.0.11
  intl: ^0.20.2
  convex_bottom_bar: ^3.2.0
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2

  permission_handler: ^12.0.1

  vibration: ^3.1.3
  marquee: ^2.3.0
  animate_do: ^4.2.0
  carousel_slider: ^5.1.1
  animated_widgets: ^1.1.0
  animated_size_and_fade: ^5.1.1
  shimmer: ^3.0.0
  audioplayers: ^6.5.0
  firebase_database: ^11.3.10
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  url_launcher: ^6.3.2
  fluttertoast: ^8.2.12
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.9.1
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_map: ^8.2.1
  http: ^1.5.0
  latlong2: ^0.9.1
  location: ^8.0.1
  auto_translator: ^2.3.5
  translator: ^1.0.3+1
  confetti: ^0.8.0
  webview_flutter: ^4.13.0
  flutter_launcher_icons: ^0.14.4
  badges: ^3.1.2
  pie_chart: ^5.4.0
  fl_chart: ^0.69.0
  flutter_polyline_points: ^2.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pic/Kaamwala.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/pic/Kaamwala.png"
  min_sdk_android: 21


# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/pic/Kaamwala.png"   # <-- yahan apna icon ka path do
#   min_sdk_android: 21


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/pic/


  # To add assets to your application, add an assets section, like this:
 
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
